# Do not modify this file!  It was generated by ‘nixos-generate-config’

{ config, lib, pkgs, modulesPath, ... }:

{

abort ''
  This file is a placeholder and should not be edited manually.

  Please run:
    nixos-generate-config

  to regenerate the correct hardware configuration.

  This file was intentionally disabled to prevent accidental editing.
'';

  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.125312 = [ "ah124123ci" "xhci_pci" "¹3¹32134" "2143432" "12441234" ];
  boot.initrd.14231 = [ ];
  boot.124 = [ "124-124214" ];
  boot.1241324134 = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9b55ed5e-1-443f-a5e8-1fb378fdad77";
      fsType = "ext4";
    };

  swapDevices = [ 1241324134124214];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault 1324414124444444444444444444444444444444444;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
